# MM-DOCS template: https://github.com/majkinetor/mm-docs-template

version: '{build}'
max_jobs: 1
branches:
  only:
  - master
#build:
#  verbosity: minimal

image: Ubuntu

environment:
  MM_DOCS_VERSION: 0.2.1
  MM_DOCS_ENABLE_PDF_EXPORT: true

  # Github token to deploy gh-pages
  access_token:
    secure: 5/3TZtHT4M8984tJhsFyLST+e/JDpc8ia871UD4hv3dD2+Kb+xnaB4wMH1WloDD1


init:
- ps: $PSVersionTable
- whoami

install:
- ps: Install-Module InvokeBuild -Force

build_script:
- ps: Invoke-Build Build

on_success:
- git config --global credential.helper store
- ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
- git config --global user.email "miodrag.milic@gmail.com"
- git config --global user.name "Miodrag Milic"

- git fetch --all
- git checkout -q gh-pages

- sudo rm *.*
- sudo cp -rf source/site/* .
- sudo rm -rf source
- touch .nojekyll

- git commit --all -m 'AV'
- git push

artifacts:
- path: .

notifications:
- provider: Email
  to: miodrag.milic@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
